# Generated by Django 4.0.5 on 2022-09-01 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name']},
        ),
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='subgenre',
            options={'ordering': ['genre__name', 'name']},
        ),
        migrations.AddField(
            model_name='book',
            name='audiobook',
            field=models.BooleanField(default=False),
        ),
    ]
