# Generated by Django 4.0.8 on 2023-03-29 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_book_tags'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AlterUniqueTogether(
            name='book',
            unique_together={('title', 'year')},
        ),
    ]
