# Generated by Django 4.0.10 on 2024-06-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subgenre',
            name='exclude_from_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
