# Generated by Django 4.0.10 on 2025-10-14 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_subgenre_exclude_from_challenge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
